### ISSUE TITLE
Failing to create loadbalancer on shared network with global routing mode set to true

### ISSUE THREAD

**Issue by szakeri** [F5Networks/f5-openstack-lbaasv2-driver#227]
* Details: 
I ran into this problem as part of running Tempest scenario test with overcloud stack.

#### Agent Version
9.0.2

#### Description
2Ish016-08-23 13:28:30.461 22856 ERROR neutron_lbaas.services.loadbalancer.plugin     driver_method(context, db_entity)
2016-08-23 13:28:30.461 22856 ERROR neutron_lbaas.services.loadbalancer.plugin   File "/usr/lib/python2.7/site-packages/neutron_lbaas/drivers/f5/driver_v2.py", line 78, in create
2016-08-23 13:28:30.461 22856 ERROR neutron_lbaas.services.loadbalancer.plugin     self.driver.f5.loadbalancer.create(context, lb)
2016-08-23 13:28:30.461 22856 ERROR neutron_lbaas.services.loadbalancer.plugin   File "/usr/lib/python2.7/site-packages/oslo_log/helpers.py", line 46, in wrapper
2016-08-23 13:28:30.461 22856 ERROR neutron_lbaas.services.loadbalancer.plugin     return method(*args, **kwargs)
2016-08-23 13:28:30.461 22856 ERROR neutron_lbaas.services.loadbalancer.plugin   File "/usr/lib/python2.7/site-packages/f5lbaasdriver/v2/bigip/driver_v2.py", line 156, in create
2016-08-23 13:28:30.461 22856 ERROR neutron_lbaas.services.loadbalancer.plugin     raise e
2016-08-23 13:28:30.461 22856 ERROR neutron_lbaas.services.loadbalancer.plugin KeyError: 'f5_common_external_networks'
2016-08-23 13:28:30.461 22856 ERROR neutron_lbaas.services.loadbalancer.plugin
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource [req-90f54ca3-7da4-4305-ba56-26c45b55627f 56177efedad6472faf9aa832f3021bd9 a7b276b291884778881db97fb9466923 - - -] create failed
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource Traceback (most recent call last):
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 84, in resource
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource     result = method(request=request, **args)
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 410, in create
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource     return self._create(request, body, **kwargs)
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 148, in wrapper
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource     ectxt.value = e.inner_exc
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource     self.force_reraise()
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource     six.reraise(self.type_, self.value, self.tb)
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 138, in wrapper
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource     return f(*args, **kwargs)
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 521, in _create
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource     obj = do_create(body)
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 503, in do_create
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource     request.context, reservation.reservation_id)
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource     self.force_reraise()
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource     six.reraise(self.type_, self.value, self.tb)
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 496, in do_create
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource     return obj_creator(request.context, **kwargs)
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron_lbaas/services/loadbalancer/plugin.py", line 583, in create_loadbalancer
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource     self._call_driver_operation(context, create_method, lb_db)
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron_lbaas/services/loadbalancer/plugin.py", line 494, in _call_driver_operation
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource     raise loadbalancerv2.DriverError()
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource DriverError: An error happened in the driver
2016-08-23 13:28:30.475 22856 ERROR neutron.api.v2.resource
2016-08-23 13:28:30.476 22856 INFO neutron.wsgi [req-90f54ca3-7da4-4305-ba56-26c45b55627f 56177efedad6472faf9aa832f3021bd9 a7b276b291884778881db97fb9466923 - - -] 10.190.4.119 - - [23/Aug/2016 13:28:30] "POST /v2.0/lbaas/loadbalancers.json HTTP/1.1" 500 334 0.657071

**Comment by richbrowne** [comment]
The issue is in the way we check for configuration when the service definition is built.  The code assumes that the the key f5_common_external_networks should be defined.  This is not the case in global routed mode.
