### ISSUE TITLE
Issuing a loadbalancer delete on a loadbalacner in PENDING_CREATE should change the state of the loadbalacner to PENDING_DELETE

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-openstack-lbaasv2-driver#455]
#### Agent Version
9.0.2

#### Operating System
RHEL 7.3 - OSPv9

#### OpenStack Release
Mitaka

#### Bug Severity 
Severity: 5

#### Description
When a request to delete a loadbalancer is issued against a loadbalancer in the PENDING_CREATE state (which can happen and persist if the agent errors and does not update the loadbalancer properly), the plugin should alter the loadbalance status to PENDING_DELETE and try to delete the loadbalancer rather then simply raising an error that a loadbalancer in PENDING_CREATE can not be deleted.

#### Deployment
Simple to reproduce even without an error.. Just shut down your agent. Issue a loadbalancer create and then immediately issues a loadbalancer delete. 

#### OpenStack Release
OSPv9 running community tempest test creates errors which leave loadbalancers in PENDING_CREATE which can not be cleaned up with out working with the database.

**Comment by jgruber** [comment]
BIt more detail. A create loadbalancer request which passed validation and was put in the database via the community LBaaS code, but which cases issues with the service builder leaves the loadbalancer object in the wrong state. 

Here are three community tempest tests which cause this problem:

'''
neutron_lbaas.tests.tempest.v2.api.test_load_balancers_admin.LoadBalancersTestJSON.test_create_load_balancer_for_another_tenant[smoke]
neutron_lbaas.tests.tempest.v2.api.test_load_balancers_admin.LoadBalancersTestJSON.test_create_load_balancer_missing_tenant_id_field_for_admin[smoke]
neutron_lbaas.tests.tempest.v2.api.test_load_balancers_admin.LoadBalancersTestJSON.test_create_load_balancer_missing_tenant_id_for_other_tenant[smoke]
'''

As these are smoke tests they make us fail BVT.

From the neutron server log:

2017-02-27 14:31:29.525 31813 ERROR f5lbaasdriver.v2.bigip.plugin_rpc [req-0470b770-2e5c-49c1-9c33-643cef01d70a - - - - -] Exception: get_service_by_loadbalancer_id: Tenant Id of network and loadbalancer mismatched

The current behavior:

create loadbalancer->neutron server->DB->plugin->agent
agent->plugin-rpc(get_service_by_loadbalancer_id) Exception Raise->agent.

The appropriate behavior

create loadbalancer->neutron server->DB->plugin->agent
agent->plugin-rpc(get_service_by_loadbalancer_id) Exception Raise->agent
agent->plugin-rpc(update_loadbalancer_status)->plugin->DB (provisioning_status=ERROR)

**Comment by jgruber** [comment]
From the /var/log/neutron/server.log on the controller..  Some added details:

'''
2017-02-27 15:07:15.553 32233 ERROR f5lbaasdriver.v2.bigip.service_builder [req-f71876e9-ac37-48ff-9b05-5c0c5a0409ec 2bda65d3baa84fa7a29b6f5449663093 dc943f0e517a40ab939a172bc0935296 - - -] Creating a loadbalancer cd40dc96-b07d-4cf1-93ba-afd9ae719442 for tenant deffb4d7c0584e89a8ec99551565713c on a  non-shared network c220b7bd-6199-401b-9184-7a7a6e5d2ba8 owned by a6601c8e9fbe48ccac00bea542267f4e.
2017-02-27 15:07:15.554 32233 ERROR f5lbaasdriver.v2.bigip.driver_v2 [req-f71876e9-ac37-48ff-9b05-5c0c5a0409ec 2bda65d3baa84fa7a29b6f5449663093 dc943f0e517a40ab939a172bc0935296 - - -] Exception: update_loadbalancer_stats: Tenant Id of network and loadbalancer mismatched
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource [req-f71876e9-ac37-48ff-9b05-5c0c5a0409ec 2bda65d3baa84fa7a29b6f5449663093 dc943f0e517a40ab939a172bc0935296 - - -] stats failed
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource Traceback (most recent call last):
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 84, in resource
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource     result = method(request=request, **args)
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 148, in wrapper
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource     ectxt.value = e.inner_exc
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource     self.force_reraise()
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource     six.reraise(self.type_, self.value, self.tb)
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 138, in wrapper
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource     return f(*args, **kwargs)
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 217, in _handle_action
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource     ret_value = getattr(self._plugin, name)(*arg_list, **kwargs)
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron_lbaas/services/loadbalancer/plugin.py", line 1055, in stats
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource     stats_data = driver.load_balancer.stats(context, lb)
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron_lbaas/drivers/f5/driver_v2.py", line 93, in stats
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource     return self.driver.f5.loadbalancer.stats(context, lb)
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_log/helpers.py", line 46, in wrapper
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource     log.debug('%(caller)s method %(method_name)s '
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/f5lbaasdriver/v2/bigip/driver_v2.py", line 280, in stats
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource     raise e
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource F5MismatchedTenants: Tenant Id of network and loadbalancer mismatched
2017-02-27 15:07:15.555 32233 ERROR neutron.api.v2.resource 
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors [req-f71876e9-ac37-48ff-9b05-5c0c5a0409ec 2bda65d3baa84fa7a29b6f5449663093 dc943f0e517a40ab939a172bc0935296 - - -] An error occurred during processing the request: GET /v2.0/lbaas/loadbalancers/cd40dc96-b07d-4cf1-93ba-afd9ae719442/stats.json HTTP/1.0
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Type: text/plain
Host: 10.105.182.41:9696
User-Agent: python-neutronclient
X-Auth-Token: 76f40fe6dc004f359d08771b8d200ac6
X-Domain-Id: None
X-Domain-Name: None
X-Identity-Status: Confirmed
X-Project-Domain-Id: default
X-Project-Domain-Name: Default
X-Project-Id: dc943f0e517a40ab939a172bc0935296
X-Project-Name: service
X-Role: admin,ResellerAdmin,_member_
X-Roles: admin,ResellerAdmin,_member_
X-Service-Catalog: [{"endpoints": [{"adminURL": "http://10.105.182.41:8386/v1.1/dc943f0e517a40ab939a172bc0935296", "region": "regionOne", "internalURL": "http://10.105.182.41:8386/v1.1/dc943f0e517a40ab939a172bc0935296", "publicURL": "http://10.105.181.40:8386/v1.1/dc943f0e517a40ab939a172bc0935296"}], "type": "data-processing", "name": "sahara"}, {"endpoints": [{"adminURL": "http://10.105.182.41:8777/", "region": "regionOne", "internalURL": "http://10.105.182.41:8777/", "publicURL": "http://10.105.181.40:8777/"}], "type": "metering", "name": "ceilometer"}, {"endpoints": [{"adminURL": "http://10.105.182.41:8776/v1/dc943f0e517a40ab939a172bc0935296", "region": "regionOne", "internalURL": "http://10.105.182.41:8776/v1/dc943f0e517a40ab939a172bc0935296", "publicURL": "http://10.105.181.40:8776/v1/dc943f0e517a40ab939a172bc0935296"}], "type": "volume", "name": "cinder"}, {"endpoints": [{"adminURL": "http://10.105.184.40:9292/", "region": "regionOne", "internalURL": "http://10.105.184.40:9292/", "publicURL": "http://10.105.181.40:9292/"}], "type": "image", "name": "glance"}, {"endpoints": [{"adminURL": "http://10.105.181.40:35357/v2.0", "region": "regionOne", "internalURL": "http://10.105.182.41:5000/v2.0", "publicURL": "http://10.105.181.40:5000/v2.0"}], "type": "identity", "name": "keystone"}, {"endpoints": [{"adminURL": "http://10.105.184.40:8080/v1", "region": "regionOne", "internalURL": "http://10.105.184.40:8080/v1/AUTH_dc943f0e517a40ab939a172bc0935296", "publicURL": "http://10.105.181.40:8080/v1/AUTH_dc943f0e517a40ab939a172bc0935296"}], "type": "object-store", "name": "swift"}, {"endpoints": [{"adminURL": "http://10.105.182.41:9696/", "region": "regionOne", "internalURL": "http://10.105.182.41:9696/", "publicURL": "http://10.105.181.40:9696/"}], "type": "network", "name": "neutron"}, {"endpoints": [{"adminURL": "http://10.105.182.41:8774/v2.1/dc943f0e517a40ab939a172bc0935296", "region": "regionOne", "internalURL": "http://10.105.182.41:8774/v2.1/dc943f0e517a40ab939a172bc0935296", "publicURL": "http://10.105.181.40:8774/v2.1/dc943f0e517a40ab939a172bc0935296"}], "type": "compute", "name": "nova"}, {"endpoints": [{"adminURL": "http://10.105.182.41:8041/", "region": "regionOne", "internalURL": "http://10.105.182.41:8041/", "publicURL": "http://10.105.181.40:8041/"}], "type": "metric", "name": "gnocchi"}, {"endpoints": [{"adminURL": "http://10.105.182.41:8776/v2/dc943f0e517a40ab939a172bc0935296", "region": "regionOne", "internalURL": "http://10.105.182.41:8776/v2/dc943f0e517a40ab939a172bc0935296", "publicURL": "http://10.105.181.40:8776/v2/dc943f0e517a40ab939a172bc0935296"}], "type": "volumev2", "name": "cinderv2"}, {"endpoints": [{"adminURL": "http://10.105.182.41:8004/v1/dc943f0e517a40ab939a172bc0935296", "region": "regionOne", "internalURL": "http://10.105.182.41:8004/v1/dc943f0e517a40ab939a172bc0935296", "publicURL": "http://10.105.181.40:8004/v1/dc943f0e517a40ab939a172bc0935296"}], "type": "orchestration", "name": "heat"}, {"endpoints": [{"adminURL": "http://10.105.182.41:8042/", "region": "regionOne", "internalURL": "http://10.105.182.41:8042/", "publicURL": "http://10.105.181.40:8042/"}], "type": "alarming", "name": "aodh"}]
X-Tenant: service
X-Tenant-Id: dc943f0e517a40ab939a172bc0935296
X-Tenant-Name: service
X-User: ceilometer
X-User-Domain-Id: default
X-User-Domain-Name: Default
X-User-Id: 2bda65d3baa84fa7a29b6f5449663093
X-User-Name: ceilometer
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors Traceback (most recent call last):
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors   File "/usr/lib/python2.7/site-packages/oslo_middleware/catch_errors.py", line 38, in __call__
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors     response = req.get_response(self.application)
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1317, in send
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors     application, catch_exc_info=False)
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1281, in call_application
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors     app_iter = application(self.environ, start_response)
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 130, in __call__
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors     resp = self.call_func(req, *args, **self.kwargs)
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 195, in call_func
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors     return self.func(req, *args, **kwargs)
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors   File "/usr/lib/python2.7/site-packages/keystonemiddleware/auth_token/__init__.py", line 467, in __call__
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors     response = req.get_response(self._app)
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1317, in send
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors     application, catch_exc_info=False)
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1281, in call_application
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors     app_iter = application(self.environ, start_response)
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 144, in __call__
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors     return resp(environ, start_response)
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 144, in __call__
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors     return resp(environ, start_response)
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors   File "/usr/lib/python2.7/site-packages/routes/middleware.py", line 131, in __call__
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors     response = self.app(environ, start_response)
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 144, in __call__
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors     return resp(environ, start_response)
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 130, in __call__
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors     resp = self.call_func(req, *args, **self.kwargs)
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 195, in call_func
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors     return self.func(req, *args, **kwargs)
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 99, in resource
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors     e = translate(e, language)
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 188, in translate
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors     translatable.msg = localize(translatable.msg, locale)
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors AttributeError: 'F5MismatchedTenants' object has no attribute 'msg'
2017-02-27 15:07:15.556 32233 ERROR oslo_middleware.catch_errors 
2017-02-27 15:07:15.559 32233 INFO neutron.wsgi [req-f71876e9-ac37-48ff-9b05-5c0c5a0409ec 2bda65d3baa84fa7a29b6f5449663093 dc943f0e517a40ab939a172bc0935296 - - -] 10.105.182.44 - - [27/Feb/2017 15:07:15] "GET /v2.0/lbaas/loadbalancers/cd40dc96-b07d-4cf1-93ba-afd9ae719442/stats.json HTTP/1.1" 500 341 0.439694
'''

Note: there is no F5MismatchedTenants message on the agent. It looks like neutron RPC wants to see .msg attributes on exceptions by oslo middleware.

**Comment by richbrowne** [comment]
The mismatched tenant issue is fixed in the current 'unreleased' code.  We no longer throw an exception in the service_builder.  Instead, the service with mismatched loadbalancer tenant and subnet tenant id's is forwarded to the agent.  The agent tries to deploy the network in the admin tenant folder on the big ip and the virtual address in the loadbalancer tenant folder.  This fails and the agent will set the loadbalancer to ERROR state.

In the recent work on the HPB.  A running cache of services in PENDING state is kept on the agent.  After a configurable timeout period, default is 60 seconds, the agent stops trying to fix the pending service and puts it in 'ERROR' state.  Where the user can delete it.

commit 47d2da82c7a7bee323c511fb9fa2e007e35b6aa2
Author: Rich Browne <r.browne@f5.com>
Date:   Wed Feb 1 09:54:40 2017 -0700

    Loadbalancer stuck in 'PENDING_UPDATE' when listener created after tenant mismatch.

    Issues:
    Fixes #402

    Problem:
    When a loadbalancer is created on a network that is not shared, nor
    owned by the administrator, there is a configuration problem on the
    BigIP because the network constructs will be in a different partition
    from the LTM objects.  Network RBAC will solve this problem.

    In the near term an exception was thrown that would be thrown from
    service builder and handled in the driver.  While the loadbalancer would
    be put in ERROR state, this does not prevent a user from creating a
    listener/pool this loadbalancer.  The result is that the loadbalancer
    get's put in a 'PENDING_UPDATE' state that cannot be cleared
    because the MismatchedTenants exception prevents the agent from
    clearing up this condition.

    Analysis:
    The change is to remove the mismatched tenants exception all
    together and log the error in the server log.  The result will
    be the attempt by the agent to deploy the service will fail
    because the LTM objects are in the loadbalancer partition and the
    network objects are in the network partition.  These cannot be
    shared and will result in a loadbalancer in ERROR state.  However,
    subsequent objects created on the loadbalancer will not cause
    the lb to stick in PENDING_UPDATE.  The request will be sent to the
    agent and it will properly put the lb in ERROR state.

    Tests:
    Create an admin network and a demo network (owned by demo user)
    As admin create a loadbalancer on the demo-network -- verify lb in ERROR
    As admin, create a listener on the previous lb. -- verify lb in ERROR
    not in PENDING_UPDATE.
    As admin, remove listener -- verify removed.
    As admin, remove loadbalancer --verify removed.
    api/test_load_balancer_create.py::test_create_load_balancer_without_tenant_id

**Comment by dflanigan** [comment]
Confirm that this issue is resolved after the feature.opflex branch collapses.
