### ISSUE TITLE
Database deadlock can occur when deleting a loadbalancer

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-openstack-lbaasv2-driver#472]
#### OpenStack Release
Found on mitaka, but likely exists in liberty as well.

#### Bug Severity 
This is a rare occurrence.

#### Description
By default, a loadbalancer manages the VIP port it uses for traffic. This means part of the lb creation is creating the VIP port and allocation an IP address. Likewise, when tearing down an lb, the port is also torn down.

There are cases, such as when running tests, that we can deadlock the database by calling to delete an lb. If a test calls to delete the lb, then does not wait for the lb to be gone from the db, and goes then to actively remove the VIP port, a deadlock can occur. The lb delete operation locks a row in the lb table, which has a foreign key dependency on a port, and the test call to delete the VIP port locks a row in the ports tables. This creates the deadlock before any of the operations can complete. It is important to note that this can happen in a few situations, but this is a common one in our tests. The solution is generally just to retry the operation. If we catch the exception and retry the lb delete, this should succeed. If the lb is already gone by then, we can delete the VIP port outright.

Will update with a traceback.

**Comment by pjbreaux** [comment]
Traceback when trying to delete a loadbalancer in test `test_l7policy_rules.py::TestL7PolicyTestJSONRedirectToUrl::test_policy_redirect_url_contains`:

```
2017-03-10 11:13:42.783 53853 DEBUG f5lbaasdriver.v2.bigip.plugin_rpc [req-b562475c-6b68-49a2-ae25-b8816472ba35 - - - - -] f5lbaasdriver.v2.bigip.plugin_rpc.LBaaSv2PluginCallbacksRPC method loadbalancer_destroyed called with arguments (<neutron.context.Context object at 0x7054090>,) {u'loadbalancer_id': u'abf62ffa-2ba4-4e2c-9bc7-cc926979151b'} wrapper /usr/lib/python2.7/site-packages/oslo_log/helpers.py:45
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher [req-b562475c-6b68-49a2-ae25-b8816472ba35 - - - - -] Exception during message handling: (pymysql.err.InternalError) (1213, u'Deadlock found when trying to get lock; try restarting transaction') [SQL: u'DELETE FROM lbaas_loadbalancer_statistics WHERE lbaas_loadbalancer_statistics.loadbalancer_id = %(loadbalancer_id)s'] [parameters: {'loadbalancer_id': u'abf62ffa-2ba4-4e2c-9bc7-cc926979151b'}]
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher Traceback (most recent call last):
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 138, in _dispatch_and_reply
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     incoming.message))
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 185, in _dispatch
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     return self._do_dispatch(endpoint, method, ctxt, args)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 127, in _do_dispatch
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     result = func(ctxt, **new_args)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/oslo_log/helpers.py", line 46, in wrapper
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     return method(*args, **kwargs)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/f5lbaasdriver/v2/bigip/plugin_rpc.py", line 271, in loadbalancer_destroyed
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     self.driver.plugin.db.delete_loadbalancer(context, loadbalancer_id)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/neutron_lbaas/db/loadbalancer/loadbalancer_dbv2.py", line 242, in delete_loadbalancer
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     context.session.delete(lb_db)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 502, in __exit__
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     self.rollback()
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     compat.reraise(exc_type, exc_value, exc_tb)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 499, in __exit__
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     self.commit()
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     self._prepare_impl()
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     self.session.flush()
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2027, in flush
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     self._flush(objects)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2145, in _flush
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     transaction.rollback(_capture_exception=True)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     compat.reraise(exc_type, exc_value, exc_tb)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2109, in _flush
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     flush_context.execute()
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     rec.execute(self)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 561, in execute
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     uow
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 249, in delete_obj
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     cached_connections, mapper, table, delete)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 892, in _emit_delete_statements
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     c = connection.execute(statement, del_objects)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     return meth(self, multiparams, params)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     return connection._execute_clauseelement(self, multiparams, params)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     compiled_sql, distilled_params
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     context)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1337, in _handle_dbapi_exception
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     util.raise_from_cause(newraise, exc_info)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     reraise(type(exception), exception, tb=exc_tb)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     context)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     cursor.execute(statement, parameters)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 166, in execute
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     result = self._query(query)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 322, in _query
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     conn.query(q)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 841, in query
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1029, in _read_query_result
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     result.read()
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1312, in read
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     first_packet = self.connection._read_packet()
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 991, in _read_packet
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     packet.check_error()
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     err.raise_mysql_exception(self._data)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher     raise errorclass(errno, errval)
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher DBDeadlock: (pymysql.err.InternalError) (1213, u'Deadlock found when trying to get lock; try restarting transaction') [SQL: u'DELETE FROM lbaas_loadbalancer_statistics WHERE lbaas_loadbalancer_statistics.loadbalancer_id = %(loadbalancer_id)s'] [parameters: {'loadbalancer_id': u'abf62ffa-2ba4-4e2c-9bc7-cc926979151b'}]
2017-03-10 11:13:42.920 53853 ERROR oslo_messaging.rpc.dispatcher
2017-03-10 11:13:42.948 53853 DEBUG neutron.plugins.ml2.plugin [req-b562475c-6b68-49a2-ae25-b8816472ba35 - - - - -] Deleting port 63097b67-13a8-4ca6-bc48-2dd0d8ce8748 _pre_delete_port /usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py:1391
2017-03-10 11:13:42.948 53853 DEBUG neutron.callbacks.manager [req-b562475c-6b68-49a2-ae25-b8816472ba35 - - - - -] Notify callbacks for port, before_delete _notify_loop /usr/lib/python2.7/site-packages/neutron/callbacks/manager.py:138
2017-03-10 11:13:42.949 53853 DEBUG neutron.callbacks.manager [req-b562475c-6b68-49a2-ae25-b8816472ba35 - - - - -] Calling callback neutron_lbaas.db.loadbalancer.loadbalancer_dbv2._prevent_lbaasv2_port_delete_callback _notify_loop /usr/lib/python2.7/site-packages/neutron/callbacks/manager.py:145
2017-03-10 11:13:42.973 53853 DEBUG neutron.callbacks.manager [req-b562475c-6b68-49a2-ae25-b8816472ba35 - - - - -] Calling callback neutron.db.l3_db._prevent_l3_port_delete_callback _notify_loop /usr/lib/python2.7/site-packages/neutron/callbacks/manager.py:145
```

**Comment by pjbreaux** [comment]
This is not a test-bug. This is a product issue. @dflanigan

**Comment by pjbreaux** [comment]
Another way this problem can show up is doing an lb create and delete via the CLI. The deadlock does not always occur, as timing is involved, but I can get it disappear by commenting out the line:

https://github.com/F5Networks/f5-openstack-agent/blob/mitaka/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py#L1312

The update_loadbalancer_status line is duplicated in the above function, and the service object does contain an lb with PENDING_DELETE provisioning_status, so we call back to the driver twice to perform the same operation. If things move too quickly for the neutron database, we can get a deadlock.

https://github.com/F5Networks/f5-openstack-agent/blob/mitaka/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py#L1312

**Comment by ssorenso** [comment]
I've reproduced this while using strace on both the neutron-lbaas-agent as well as f5-openstack-agent.

The logs are [here in this .tar.gz](https://github.com/F5Networks/f5-openstack-lbaasv2-driver/files/851734/deadlock_issue.tar.gz).

**Comment by mattgreene** [comment]
Dropping priority on this issue until we resolve the RPC hang and see if the nightly becomes stable.

**Comment by mattgreene** [comment]
Resolved via https://github.com/F5Networks/f5-openstack-agent/pull/644
