### ISSUE TITLE
Running Driver nightly tests fails against undercloud deployment - Newton Qual

### ISSUE THREAD

**Issue by szakeri** [F5Networks/f5-openstack-lbaasv2-driver#552]
* Details: For bugs, copy and paste the following template into your new issue and fill it out.
Running Driver nightly tests fails against undercloud newton stack, This is the log message in f5-opesntack-agent.log:
```

ext: u'{"code":404,"message":"01020036:3: The requested self IP (/Project_57dd3ea01116482ca95d9fd6e1153a2e/local-bigip1-e03cad40-cc4a-4265-b348-c3236d96908d) was not found.","errorStack":[],"apiError":3}' wrapper /usr/lib/python2.7/site-packages/icontrol/session.py:265
2017-05-04 09:50:46.579 43583 DEBUG root [req-ab6c6c10-265a-4efc-aa67-9bf3c73dada6 8d03583ac05d468ebae3aa6f4e117beb cc57ed7b62344129bb4f85fbc3722b10 - - -] post WITH uri: https://10.190.7.248:443/mgmt/tm/net/self/ AND suffix:  AND kwargs: {'json': {'floating': 'disabled', 'vlan': 'tunnel-vxlan-39', 'partition': u'Project_57dd3ea01116482ca95d9fd6e1153a2e', 'name': u'local-bigip1-e03cad40-cc4a-4265-b348-c3236d96908d', 'address': '%2/28'}} wrapper /usr/lib/python2.7/site-packages/icontrol/session.py:257
2017-05-04 09:50:46.592 43583 DEBUG root [req-ab6c6c10-265a-4efc-aa67-9bf3c73dada6 8d03583ac05d468ebae3aa6f4e117beb cc57ed7b62344129bb4f85fbc3722b10 - - -] RESPONSE::STATUS: 400 Content-Type: application/json Content-Encoding: None
Text: u'{"code":400,"message":"\\"%2/28\\" invalid address","errorStack":[],"apiError":26214401}' wrapper /usr/lib/python2.7/site-packages/icontrol/session.py:265
2017-05-04 09:50:46.592 43583 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.selfips [req-ab6c6c10-265a-4efc-aa67-9bf3c73dada6 8d03583ac05d468ebae3aa6f4e117beb cc57ed7b62344129bb4f85fbc3722b10 - - -] selfip creation error: 400 Unexpected Error: Bad Request for uri: https://10.190.7.248:443/mgmt/tm/net/self/
Text: u'{"code":400,"message":"\\"%2/28\\" invalid address","errorStack":[],"apiError":26214401}'(400)
2017-05-04 09:50:46.592 43583 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.selfips Traceback (most recent call last):
2017-05-04 09:50:46.592 43583 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.selfips   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/selfips.py", line 50, in _create_bigip_selfip
2017-05-04 09:50:46.592 43583 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.selfips     self.selfip_manager.create(bigip, model)
2017-05-04 09:50:46.592 43583 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.selfips   File "/usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/resource_helper.py", line 94, in create
2017-05-04 09:50:46.592 43583 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.selfips     obj = resource.create(**model)
2017-05-04 09:50:46.592 43583 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.selfips   File "/usr/lib/python2.7/site-packages/f5/bigip/resource.py", line 974, in create
2017-05-04 09:50:46.592 43583 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.selfips     return self._create(**kwargs)
2017-05-04 09:50:46.592 43583 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.selfips   File "/usr/lib/python2.7/site-packages/f5/bigip/resource.py", line 941, in _create
2017-05-04 09:50:46.592 43583 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.selfips     response = session.post(_create_uri, json=kwargs, **requests_params)
2017-05-04 09:50:46.592 43583 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.selfips   File "/usr/lib/python2.7/site-packages/icontrol/session.py", line 272, in wrapper
2017-05-04 09:50:46.592 43583 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.selfips     raise iControlUnexpectedHTTPError(error_message, response=response)
2017-05-04 09:50:46.592 43583 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.selfips iControlUnexpectedHTTPError: 400 Unexpected Error: Bad Request for uri: https://10.190.7.248:443/mgmt/tm/net/self/
2017-05-04 09:50:46.592 43583 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.selfips Text: u'{"code":400,"message":"\\"%2/28\\" invalid address","errorStack":[],"apiError":26214401}'
2017-05-04 09:50:46.592 43583 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.selfips
2017-05-04 09:50:46.593 43583 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-ab6c6c10-265a-4efc-aa67-9bf3c73dada6 8d03583ac05d468ebae3aa6f4e117beb cc57ed7b62344129bb4f85fbc3722b10 - - -] Prep-network exception: icontrol_driver: 400 Unexpected Error: Bad Request for uri: https://10.190.7.248:443/mgmt/tm/net/self/
Text: u'{"code":400,"message":"\\"%2/28\\" invalid address","errorStack":[],"apiError":26214401}'
2017-05-04 09:50:46.594 43583 DEBUG f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-ab6c6c10-265a-4efc-aa67-9bf3c73dada6 8d03583ac05d468ebae3aa6f4e117beb cc57ed7b62344129bb4f85fbc3722b10 - - -]     _prep_service_networking took 0.31975 secs _common_service_handler /usr/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py:1233


```
#### OpenStack Release
Newton

#### Bug Severity 
For bugs enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

* Details: For enhancements, copy and paste the following template into your new issue and fill it out.

**Comment by pjbreaux** [comment]
@dflanigan: please remove test bug from this issue. We don't believe it is a test bug. It is very likely a code fix that must go into either the driver or agent to get a service deployed in newton undercloud.

**Comment by pjbreaux** [comment]
@szakeri: do you recall the failing test for this issue?

**Comment by pjbreaux** [comment]
@szakeri: I'm closing this issue, as it has been addressed in newton.
