### ISSUE TITLE
Details: Request Failed: internal server error while processing your request.

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-openstack-lbaasv2-driver#592]
liberty_12.1.1_undercloud_vxlan

The three associated tests failed in nightly 2017-06-02, but *not* in a manual run.

All three reference an internal error, associated with a "delete loadbalancer" operation.

```
name:	test_update_health_monitor_missing_url_path
description:	Test update health monitor with missing url_path field
result:	fail
failure msg:	../../../../../.tox/apiv2/local/lib/python2.7/site-packages/tempest/test.py:318: in tearDownClass
    six.reraise(etype, value, trace)
../../../../../.tox/apiv2/local/lib/python2.7/site-packages/tempest/test.py:301: in tearDownClass
    teardown()
base.py:109: in resource_cleanup
    cls._try_delete_resource(cls._delete_load_balancer, lb_id)
../../../../../.tox/apiv2/local/lib/python2.7/site-packages/tempest/api/network/base.py:150: in _try_delete_resource
    delete_callable(*args, **kwargs)
base.py:147: in _delete_load_balancer
    load_balancer_id, delete=True)
base.py:170: in _wait_for_load_balancer_status
    load_balancer_id)
../clients/load_balancers_client.py:40: in get_load_balancer
    resp, body = self.get(url)
../../../../../.tox/apiv2/local/lib/python2.7/site-packages/tempest/lib/common/rest_client.py:274: in get
    return self.request('GET', url, extra_headers, headers)
../../../../../.tox/apiv2/local/lib/python2.7/site-packages/tempest/lib/common/rest_client.py:641: in request
    resp, resp_body)
../../../../../.tox/apiv2/local/lib/python2.7/site-packages/tempest/lib/common/rest_client.py:760: in _error_checker
    message=message)
E ServerFault: Got server fault
E Details: Request Failed: internal server error while processing your request.
```

```
name:	test_create_load_balancer
description:	Test create load balancer
result:	fail
failure msg:	NOTE: Incompatible Exception Representation, displaying natively:

_StringException: pythonlogging:'': {{{
2017-06-02 01:15:01,108 18034 INFO     [tempest.lib.common.rest_client] Request (LoadBalancersTestJSON:test_create_load_balancer): 201 POST http://10.190.4.156:9696/v2.0/lbaas/loadbalancers 0.652s
2017-06-02 01:15:01,239 18034 INFO     [tempest.lib.common.rest_client] Request (LoadBalancersTestJSON:test_create_load_balancer): 200 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/1f4f2c2a-fb74-474f-b051-e6ca3ee2d8a8 0.131s
2017-06-02 01:15:02,426 18034 INFO     [tempest.lib.common.rest_client] Request (LoadBalancersTestJSON:test_create_load_balancer): 200 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/1f4f2c2a-fb74-474f-b051-e6ca3ee2d8a8 0.185s
2017-06-02 01:15:02,518 18034 INFO     [tempest.lib.common.rest_client] Request (LoadBalancersTestJSON:test_create_load_balancer): 200 GET http://10.190.4.156:9696/v2.0/ports/285f3a9f-6102-41bc-8409-3a54134a96ef 0.091s
2017-06-02 01:15:02,646 18034 INFO     [tempest.lib.common.rest_client] Request (LoadBalancersTestJSON:test_create_load_balancer): 200 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/1f4f2c2a-fb74-474f-b051-e6ca3ee2d8a8 0.128s
2017-06-02 01:15:02,705 18034 INFO     [tempest.lib.common.rest_client] Request (LoadBalancersTestJSON:test_create_load_balancer): 200 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/1f4f2c2a-fb74-474f-b051-e6ca3ee2d8a8 0.058s
2017-06-02 01:15:02,706 18034 INFO     [neutron_lbaas.tests.tempest.v2.api.test_load_balancers_non_admin:LoadBalancersTestJSON] Finished: test_create_load_balancer

2017-06-02 01:15:02,975 18034 INFO     [tempest.lib.common.rest_client] Request (LoadBalancersTestJSON:_run_cleanups): 204 DELETE http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/1f4f2c2a-fb74-474f-b051-e6ca3ee2d8a8 0.269s
2017-06-02 01:15:03,025 18034 INFO     [tempest.lib.common.rest_client] Request (LoadBalancersTestJSON:_run_cleanups): 200 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/1f4f2c2a-fb74-474f-b051-e6ca3ee2d8a8 0.050s
2017-06-02 01:15:04,066 18034 INFO     [tempest.lib.common.rest_client] Request (LoadBalancersTestJSON:_run_cleanups): 500 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/1f4f2c2a-fb74-474f-b051-e6ca3ee2d8a8 0.039s
}}}

Traceback (most recent call last):
File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/api/base.py", line 147, in _delete_load_balancer
    load_balancer_id, delete=True)
File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/api/base.py", line 170, in _wait_for_load_balancer_status
    load_balancer_id)
File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/clients/load_balancers_client.py", line 40, in get_load_balancer
    resp, body = self.get(url)
File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/tempest/lib/common/rest_client.py", line 274, in get
    return self.request('GET', url, extra_headers, headers)
File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/tempest/lib/common/rest_client.py", line 641, in request
    resp, resp_body)
File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/tempest/lib/common/rest_client.py", line 760, in _error_checker
    message=message)
tempest.lib.exceptions.ServerFault: Got server fault
Details: Request Failed: internal server error while processing your request.
```

```
name:	test_delete_load_balancer
description:	Test delete load balancer
result:	fail
failure msg:	NOTE: Incompatible Exception Representation, displaying natively:

_StringException: pythonlogging:'': {{{
2017-06-02 01:15:45,936 18034 INFO     [tempest.lib.common.rest_client] Request (LoadBalancersTestJSON:test_delete_load_balancer): 201 POST http://10.190.4.156:9696/v2.0/lbaas/loadbalancers 0.683s
2017-06-02 01:15:46,004 18034 INFO     [tempest.lib.common.rest_client] Request (LoadBalancersTestJSON:test_delete_load_balancer): 200 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/92cd39f4-bb06-4a65-bfc4-10d0f18e55ba 0.056s
2017-06-02 01:15:47,084 18034 INFO     [tempest.lib.common.rest_client] Request (LoadBalancersTestJSON:test_delete_load_balancer): 200 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/92cd39f4-bb06-4a65-bfc4-10d0f18e55ba 0.077s
2017-06-02 01:15:48,152 18034 INFO     [tempest.lib.common.rest_client] Request (LoadBalancersTestJSON:test_delete_load_balancer): 200 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/92cd39f4-bb06-4a65-bfc4-10d0f18e55ba 0.066s
2017-06-02 01:15:48,262 18034 INFO     [tempest.lib.common.rest_client] Request (LoadBalancersTestJSON:test_delete_load_balancer): 200 GET http://10.190.4.156:9696/v2.0/ports/80e1bb31-4114-4091-bb2a-14e746e7b685 0.110s
2017-06-02 01:15:48,320 18034 INFO     [tempest.lib.common.rest_client] Request (LoadBalancersTestJSON:test_delete_load_balancer): 200 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/92cd39f4-bb06-4a65-bfc4-10d0f18e55ba 0.057s
2017-06-02 01:15:48,368 18034 INFO     [tempest.lib.common.rest_client] Request (LoadBalancersTestJSON:test_delete_load_balancer): 200 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/92cd39f4-bb06-4a65-bfc4-10d0f18e55ba 0.047s
2017-06-02 01:15:48,626 18034 INFO     [tempest.lib.common.rest_client] Request (LoadBalancersTestJSON:test_delete_load_balancer): 204 DELETE http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/92cd39f4-bb06-4a65-bfc4-10d0f18e55ba 0.257s
2017-06-02 01:15:48,674 18034 INFO     [tempest.lib.common.rest_client] Request (LoadBalancersTestJSON:test_delete_load_balancer): 200 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/92cd39f4-bb06-4a65-bfc4-10d0f18e55ba 0.047s
2017-06-02 01:15:49,697 18034 INFO     [tempest.lib.common.rest_client] Request (LoadBalancersTestJSON:test_delete_load_balancer): 500 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/92cd39f4-bb06-4a65-bfc4-10d0f18e55ba 0.021s
2017-06-02 01:15:49,698 18034 INFO     [neutron_lbaas.tests.tempest.v2.api.test_load_balancers_non_admin:LoadBalancersTestJSON] Finished: test_delete_load_balancer
}}}

Traceback (most recent call last):
File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/api/test_load_balancers_non_admin.py", line 441, in test_delete_load_balancer
    self._delete_load_balancer(new_load_balancer_id)
File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/api/base.py", line 147, in _delete_load_balancer
    load_balancer_id, delete=True)
File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/api/base.py", line 170, in _wait_for_load_balancer_status
    load_balancer_id)
File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/clients/load_balancers_client.py", line 40, in get_load_balancer
    resp, body = self.get(url)
File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/tempest/lib/common/rest_client.py", line 274, in get
    return self.request('GET', url, extra_headers, headers)
File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/tempest/lib/common/rest_client.py", line 641, in request
    resp, resp_body)
File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/tempest/lib/common/rest_client.py", line 760, in _error_checker
    message=message)
tempest.lib.exceptions.ServerFault: Got server fault
Details: Request Failed: internal server error while processing your request.
```

Associated Tests:
["neutron_lbaas.tests.tempest.v2.api.test_health_monitors_non_admin.testhealthmonitors:: test_update_health_monitor_missing_url_path",
 "neutron_lbaas.tests.tempest.v2.api.test_load_balancers_non_admin.loadbalancerstestjson:: test_create_load_balancer",
 "neutron_lbaas.tests.tempest.v2.api.test_load_balancers_non_admin.loadbalancerstestjson:: test_delete_load_balancer"]

**Comment by ssorenso** [comment]
md5sum: 0f5c4e7e445eb0d94a9654f83790d634

**Comment by ssorenso** [comment]
Additional test instances impacted:
* `openstack_driver_liberty_11.5.4-undercloud-vxlan.79.consoleText.LoadBalancersTestJSON.test_update_load_balancer_invalid_name`
* `openstack_driver_liberty_12.1.1-undercloud-vxlan.99.consoleText.LoadBalancersTestJSON.test_update_load_balancer_invalid_name`
* `openstack_driver_liberty_11.6.1-undercloud-vxlan.82.consoleText.LoadBalancersTestJSON.test_update_load_balancer_invalid_name`
sum: 4c4b8528079374ffbe97851b71a5a821
