### ISSUE TITLE
Intermittent (nightly) pool deletion failure

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-openstack-lbaasv2-driver#593]
liberty_12.1.1_undercloud_vxlan

The associated test failed in nightly 2017-06-02, but *not* in a manual run.   It seems likely the root cause is the same as, or closely related to:   #592

In all cases it appears that resource deletion is the failing operation, though, in #592 the operation is `delete loadbalancer`.

```
name:	test_delete_pool
description:	Test delete pool
result:	fail
failure msg:	NOTE: Incompatible Exception Representation, displaying natively:

_StringException: pythonlogging:'': {{{
2017-06-02 01:19:00,380 18034 INFO     [tempest.lib.common.rest_client] Request (TestPools:test_delete_pool): 200 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/76a22e59-9fdf-4bfb-b83d-2c2b82be1757 0.055s
2017-06-02 01:19:00,705 18034 INFO     [tempest.lib.common.rest_client] Request (TestPools:test_delete_pool): 201 POST http://10.190.4.156:9696/v2.0/lbaas/listeners 0.323s
2017-06-02 01:19:00,765 18034 INFO     [tempest.lib.common.rest_client] Request (TestPools:test_delete_pool): 200 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/76a22e59-9fdf-4bfb-b83d-2c2b82be1757 0.060s
2017-06-02 01:19:01,828 18034 INFO     [tempest.lib.common.rest_client] Request (TestPools:test_delete_pool): 200 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/76a22e59-9fdf-4bfb-b83d-2c2b82be1757 0.062s
2017-06-02 01:19:02,515 18034 INFO     [tempest.lib.common.rest_client] Request (TestPools:test_delete_pool): 201 POST http://10.190.4.156:9696/v2.0/lbaas/pools 0.686s
2017-06-02 01:19:02,628 18034 INFO     [tempest.lib.common.rest_client] Request (TestPools:test_delete_pool): 200 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/76a22e59-9fdf-4bfb-b83d-2c2b82be1757 0.113s
2017-06-02 01:19:03,755 18034 INFO     [tempest.lib.common.rest_client] Request (TestPools:test_delete_pool): 200 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/76a22e59-9fdf-4bfb-b83d-2c2b82be1757 0.125s
2017-06-02 01:19:03,850 18034 INFO     [tempest.lib.common.rest_client] Request (TestPools:test_delete_pool): 200 GET http://10.190.4.156:9696/v2.0/lbaas/pools/31b4c697-8cf9-40c2-a139-6acf8976c842 0.094s
2017-06-02 01:19:04,438 18034 INFO     [tempest.lib.common.rest_client] Request (TestPools:test_delete_pool): 204 DELETE http://10.190.4.156:9696/v2.0/lbaas/pools/31b4c697-8cf9-40c2-a139-6acf8976c842 0.587s
2017-06-02 01:19:04,522 18034 INFO     [tempest.lib.common.rest_client] Request (TestPools:test_delete_pool): 200 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/76a22e59-9fdf-4bfb-b83d-2c2b82be1757 0.084s
2017-06-02 01:19:04,613 18034 INFO     [tempest.lib.common.rest_client] Request (TestPools:test_delete_pool): 200 GET http://10.190.4.156:9696/v2.0/lbaas/pools/31b4c697-8cf9-40c2-a139-6acf8976c842 0.091s
2017-06-02 01:19:04,614 18034 INFO     [neutron_lbaas.tests.tempest.v2.api.test_pools_non_admin:TestPools] Finished: test_delete_pool
}}}

Traceback (most recent call last):
File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/api/test_pools_non_admin.py", line 569, in test_delete_pool
    new_pool.get('id'))
File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 434, in assertRaises
    self.assertThat(our_callable, matcher)
File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 447, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: <bound method PoolsClientJSON.get_pool of <neutron_lbaas.tests.tempest.v2.clients.pools_client.PoolsClientJSON object at 0x7fb611b765d0>> returned {u'id': u'31b4c697-8cf9-40c2-a139-6acf8976c842', u'listeners': [{u'id': u'186763fe-78ce-4709-951a-1851ac9c935f'}], u'description': u'', u'protocol': u'HTTP', u'admin_state_up': True, u'lb_algorithm': u'ROUND_ROBIN', u'tenant_id': u'fd0ee5ca60bc430288e177a86cb3f1b1', u'name': u'', u'session_persistence': None, u'healthmonitor_id': None, u'members': []}
```

Associated Tests:
["neutron_lbaas.tests.tempest.v2.api.test_pools_non_admin.testpools:: test_delete_pool"]

**Comment by ssorenso** [comment]
Re-occurance:
* `openstack_driver_liberty_12.1.1-undercloud-vxlan.99.consoleText.TestHealthMonitors.test_update_health_monitor_empty_url_path`
* Sum
  * `md5sum:e845b1b942bd304c00f4c9c99284a79e`

**Comment by ssorenso** [comment]
More re-occurrences:
* `openstack_driver_liberty_11.6.1-undercloud-vxlan.92.consoleText`
  * Type: failures
  * Test: `ListenersTestJSON.test_create_listener_empty_tenant_id`
  * Sum: `md5sum:197e3db5f1f5f23cecff0bd1a2ffc9fb`
* `openstack_driver_liberty_11.5.4-undercloud-vxlan.89.consoleText`
  * Type: failures
  * Test: `ListenersTestJSON.test_create_listener_empty_tenant_id`
  * Sum: `md5sum:59e013b4cde1860173129e5a8aa10255`

The difference in sums is due to the printed return dict's ordering, but we have:
```
Traceback (most recent call last):
  File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/api/test_listeners_admin.py", noline, in test_create_listener_empty_tenant_id
    **create_new_listener_kwargs)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", noline, in assertRaises
    self.assertThat(our_callable, matcher)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", noline, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: <bound method type._create_listener of <class 'neutron_lbaas.tests.tempest.v2.api.test_listeners_admin.ListenersTestJSON'>> returned {u'name': u'', u'id': u'352802e5-586a-46ad-8065-c5077caf162e', u'description': u'', u'default_tls_container_ref': None, u'admin_state_up': True, u'protocol_port': 8081, u'protocol': u'HTTP', u'sni_container_refs': [], u'loadbalancers': [{u'id': u'9094ad04-f89b-4fca-8efa-07a22670134b'}], u'tenant_id': u'', u'connection_limit': -1, u'default_pool_id': None}
```
For a traceback.

**Comment by dflanigan** [comment]
Could not reproduce.
