### ISSUE TITLE
Intermittent Test Infrastructure Build Issues Caused by network flakiness

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-openstack-lbaasv2-driver#742]
We lost the 11.6.1 undercloud vxlan run on Saturday for the following reason.

At 03:35:12:

```2017-08-12 03:35:12.083546: Running Command: configure_lbaasv2
2017-08-12 03:35:12.226856: ssh -q -x -i /home/jenkins/.ssh/id_rsa_testlab -o ConnectTimeout=1 -o StrictHostKeyChecking=no REDACTED@host-REDACTED /home/testlab/configure_f5-lbaasv2.sh newton undercloud `cat /home/testlab/ve_mgmt_ip` vxlan
2017-08-12 03:35:12.226976: host-REDACTED:
2017-08-12 03:35:12.351036: + STACK_DISTRO=newton
2017-08-12 03:35:12.351104: + CLOUD_DEPLOYMENT=undercloud
2017-08-12 03:35:12.351128: + BIGIP_IP=$'REDACTED\r'```

An ssh command succeeded.

Then at 03:35:38:

```2017-08-12 03:35:38.228099: + sudo systemctl restart neutron-server
Cannot contact jenkins-docker-REDACTED: java.lang.InterruptedException
Exception in thread host-REDACTED:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/tools/lib/tlc_lib.py", line 5258, in run
    sshCmd(self.name, 1, self.action, output=self.output)
  File "/tools/lib/tlc_lib.py", line 3909, in sshCmd
    raise SSHError(cmd, p.returncode, ostr)
SSHError: '/home/testlab/configure_f5-lbaasv2.sh newton undercloud `cat /home/testlab/ve_mgmt_ip` vxlan'
 => + STACK_DISTRO=newton```


The REDACTED host was the same in both instances.   So ssh works and then fails 26 seconds later.   I think we should add retries around the dev-test tlc-ssh commands.

**Comment by zancas** [comment]
The build fail on Sunday night for liberty 12.1.1 undercloud vxlan is also an SSH flake.

**Comment by dflanigan** [comment]
@ssorenso Is this still an issue ?

**Comment by ssorenso** [comment]
@dflanigan TBH, I'm not certain.  The last time that I saw this was on my analysis time of:
1503589453 - 8/24/2017 9:44:13am

I see that it occurred in the build:
driver_liberty_12.1.2-undercloud-vxlan.8

This was a hard failure that it did not recover from.  Thus, I would say that, from purely a testing analysis side, that it is too early to say definitively.
