### ISSUE TITLE
Multiple test failures regarding loadbalancer['operating_status']

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-openstack-lbaasv2-driver#748]
* Title: Multiple test failures regarding loadbalancer['operating_status']
* Attachments:
* Details:
openstack_driver_mitaka_11.5.4-undercloud-vxlan.lastSuccessfulBuild.consoleText
```
_______ TLSListenersTestJSON.test_update_listener_invalid_tls_container ________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: pythonlogging:'': {{{
2017-08-14 02:25:14,061 14202 INFO     [tempest.lib.common.rest_client] Request (TLSListenersTestJSON:test_update_listener_invalid_tls_container): 400 PUT http://10.190.4.156:9696/v2.0/lbaas/listeners/2fef00cb-b7b9-45ae-ae8e-2d36943c0954 0.011s
2017-08-14 02:25:14,171 14202 INFO     [tempest.lib.common.rest_client] Request (TLSListenersTestJSON:test_update_listener_invalid_tls_container): 200 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/f6a416d0-fdb8-4b43-87bd-10a578ff3ef4/statuses 0.110s
2017-08-14 02:25:14,172 14202 INFO     [neutron_lbaas.tests.tempest.v2.api.test_listeners_tls:TLSListenersTestJSON] Finished: test_update_listener_invalid_tls_container
}}}

Traceback (most recent call last):
  File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/api/test_listeners_tls.py", line 227, in test_update_listener_invalid_tls_container
    listener_ids=[self.listener_id])
  File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/api/base.py", line 452, in _check_status_tree
    assert 'ONLINE' == load_balancer['operating_status']
AssertionError
```

openstack_driver_liberty_11.5.4-undercloud-vxlan.79.consoleText
```
_______ TLSListenersTestJSON.test_update_listener_invalid_tls_container ________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: pythonlogging:'': {{{
2017-08-14 01:21:27,095 19914 INFO     [tempest.lib.common.rest_client] Request (TLSListenersTestJSON:test_update_listener_invalid_tls_container): 400 PUT http://10.190.4.156:9696/v2.0/lbaas/listeners/9bebc5e8-cb20-49b6-b999-b7ec3549c4dc 0.010s
2017-08-14 01:21:27,208 19914 INFO     [tempest.lib.common.rest_client] Request (TLSListenersTestJSON:test_update_listener_invalid_tls_container): 200 GET http://10.190.4.156:9696/v2.0/lbaas/loadbalancers/ce0c9b76-4cdd-4b0c-a9a4-46fa89c6e9ee/statuses 0.112s
2017-08-14 01:21:27,208 19914 INFO     [neutron_lbaas.tests.tempest.v2.api.test_listeners_tls:TLSListenersTestJSON] Finished: test_update_listener_invalid_tls_container
}}}

Traceback (most recent call last):
  File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/api/test_listeners_tls.py", line 227, in test_update_listener_invalid_tls_container
    listener_ids=[self.listener_id])
  File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/api/base.py", line 452, in _check_status_tree
    assert 'ONLINE' == load_balancer['operating_status']
AssertionError
```

openstack_driver_liberty_11.6.1-undercloud-vxlan.82.consoleText
```
_______ TLSListenersTestJSON.test_update_listener_invalid_tls_container ________
NOTE: Incompatible Exception Representation, displaying natively:

_StringException: pythonlogging:'': {{{
2017-08-14 01:19:17,418 20337 INFO     [tempest.lib.common.rest_client] Request (TLSListenersTestJSON:test_update_listener_invalid_tls_container): 400 PUT http://10.190.4.143:9696/v2.0/lbaas/listeners/6604c251-c8e3-43cc-961d-3eccaf8ab419 0.008s
2017-08-14 01:19:17,509 20337 INFO     [tempest.lib.common.rest_client] Request (TLSListenersTestJSON:test_update_listener_invalid_tls_container): 200 GET http://10.190.4.143:9696/v2.0/lbaas/loadbalancers/b8830fd8-b4cc-48c2-b449-d51d02ce135d/statuses 0.090s
2017-08-14 01:19:17,510 20337 INFO     [neutron_lbaas.tests.tempest.v2.api.test_listeners_tls:TLSListenersTestJSON] Finished: test_update_listener_invalid_tls_container
}}}

Traceback (most recent call last):
  File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/api/test_listeners_tls.py", line 227, in test_update_listener_invalid_tls_container
    listener_ids=[self.listener_id])
  File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/api/base.py", line 452, in _check_status_tree
    assert 'ONLINE' == load_balancer['operating_status']
AssertionError
```

#### Agent Version
53fdb6a6e54e8ec30771c895aac3268e82480e99

#### Operating System
nightly

#### OpenStack Release
* Liberty
* Mitaka

#### Bug Severity 
Medium (suggested)

#### Description
This occurs in the implied nightly instances

#### Deployment
Nightly

md5sums:

reduced(md5sum):becfd1b43568d817af7864bb1c52aba5
TLSListenersTestJSON.test_update_listener_invalid_tls_container
md5sum:08a5f942f1e0da1d60f669300bfefd0d
TLSListenersTestJSON.test_update_listener_empty_uuid_tls_container
md5sum:36661fc5bcbe81360a98c143d91e170a
TLSListenersTestJSON.test_update_listener_tls_port
md5sum:7cb6dfa1cb16e909647f867a2440a8ba
TLSListenersTestJSON.test_update_listener_nonexistent_tls_container
md5sum:888c8ded907358f3e074250a57ae4dd4
TLSListenersTestJSON.test_update_listener_tls_protocol
md5sum:fdca944fe26dca551a74c689fa53931b

It is not known if these should be specific to each, individual test.

**Comment by ssorenso** [comment]
test metadata:
`openstack_driver_mitaka_11.6.1-undercloud-vxlan.lastSuccessfulBuild.consoleText`
`openstack_driver_liberty_11.5.4-undercloud-vxlan.79.consoleText`
`openstack_driver_liberty_11.6.1-undercloud-vxlan.82.consoleText`
`openstack_driver_mitaka_11.5.4-undercloud-vxlan.lastSuccessfulBuild.consoleText`

**Comment by ssorenso** [comment]
more test bug instances:
* `openstack_driver_mitaka_11.5.4-undercloud-vxlan.84.consoleText`
  * Type: failures
  * Test; `TLSListenersTestJSON.test_delete_tls_listener`
* `openstack_driver_mitaka_11.5.4-undercloud-vxlan.84.consoleText`
  * Type: failures
  * `TLSListenersTestJSON.test_get_tls_listener`
* Sum: reduced(md5sum):becfd1b43568d817af7864bb1c52aba5

**Comment by ssorenso** [comment]
reduced: 6efab8b558c5b77bb7e9cf7a6894bd4c
