### ISSUE TITLE
Object creation failure due to an object already existing f5lbaasdriver.test.tempest.tests.api.test_member_subnets.MemberSubnetTestJSON

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-openstack-lbaasv2-driver#759]
* Title: Object creation failure due to an object already existing f5lbaasdriver.test.tempest.tests.api.test_member_subnets.MemberSubnetTestJSON
* Attachments: 
* Details: 

```

cls = <class 'f5lbaasdriver.test.tempest.tests.api.test_member_subnets.MemberSubnetTestJSON'>

    @classmethod
    def tearDownClass(cls):
        at_exit_set.discard(cls)
        # It should never be overridden by descendants
        if hasattr(super(BaseTestCase, cls), 'tearDownClass'):
            super(BaseTestCase, cls).tearDownClass()
        # Save any existing exception, we always want to re-raise the original
        # exception only
        etype, value, trace = sys.exc_info()
        # If there was no exception during setup we shall re-raise the first
        # exception in teardown
        re_raise = (etype is None)
        while cls.teardowns:
            name, teardown = cls.teardowns.pop()
            # Catch any exception in tearDown so we can re-raise the original
            # exception at the end
            try:
                teardown()
            except Exception as te:
                sys_exec_info = sys.exc_info()
                tetype = sys_exec_info[0]
                # TODO(andreaf): Till we have the ability to cleanup only
                # resources that were successfully setup in resource_cleanup,
                # log AttributeError as info instead of exception.
                if tetype is AttributeError and name == 'resources':
                    LOG.info("tearDownClass of %s failed: %s" % (name, te))
                else:
                    LOG.exception("teardown of %s failed: %s" % (name, te))
                if not etype:
                    etype, value, trace = sys_exec_info
        # If exceptions were raised during teardown, and not before, re-raise
        # the first one
        if re_raise and etype is not None:
            try:
>               six.reraise(etype, value, trace)

cls        = <class 'f5lbaasdriver.test.tempest.tests.api.test_member_subnets.MemberSubnetTestJSON'>
etype      = <class 'tempest.lib.exceptions.Conflict'>
name       = 'credentials'
re_raise   = True
sys_exec_info = (<class 'tempest.lib.exceptions.Conflict'>, Conflict(), <traceback object at 0x7f290c5848c0>)
te         = Conflict()
teardown   = <bound method type.clear_credentials of <class 'f5lbaasdriver.test.tempest.tests.api.test_member_subnets.MemberSubnetTestJSON'>>
tetype     = <class 'tempest.lib.exceptions.Conflict'>
value      = Conflict()

/usr/local/lib/python2.7/dist-packages/tempest/test.py:318:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/local/lib/python2.7/dist-packages/tempest/test.py:301: in tearDownClass
    teardown()
/usr/local/lib/python2.7/dist-packages/neutron_lbaas/tests/tempest/v2/api/base.py:174: in resource_cleanup
    super(BaseTestCase, cls).resource_cleanup()
/usr/local/lib/python2.7/dist-packages/tempest/api/network/base.py:128: in resource_cleanup
    subnet['id'])
/usr/local/lib/python2.7/dist-packages/neutron_lbaas/tests/tempest/v2/api/base.py:191: in _try_delete_resource
    delete_callable(*args, **kwargs)
/usr/local/lib/python2.7/dist-packages/tempest/lib/services/network/subnets_client.py:34: in delete_subnet
    return self.delete_resource(uri)
/usr/local/lib/python2.7/dist-packages/tempest/lib/services/network/base.py:41: in delete_resource
    resp, body = self.delete(req_uri)
/usr/local/lib/python2.7/dist-packages/tempest/lib/common/rest_client.py:290: in delete
    return self.request('DELETE', url, extra_headers, headers, body)
/usr/local/lib/python2.7/dist-packages/tempest/lib/common/rest_client.py:641: in request
    resp, resp_body)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tempest.lib.services.network.subnets_client.SubnetsClient object at 0x7f290c5d8810>
method = 'DELETE', url = 'v2.0/subnets/fa703afd-0154-459d-8acb-1eaa581b41a4'
headers = {'Accept': 'application/json', 'Content-Type': 'application/json'}
body = None
resp = {'content-location': 'http://10.190.4.143:9696/v2.0/subnets/fa703afd-0154-459d...pe': 'application/json; charset=UTF-8', 'connection': 'close', 'status': '409'}
resp_body = {'detail': '', 'message': 'Unable to complete operation on subnet fa703afd-0154-459d-8acb-1eaa581b41a4: One or more ports have an IP allocation from this subnet.', 'type': 'SubnetInUse'}

    def _error_checker(self, method, url,
                       headers, body, resp, resp_body):

        # NOTE(mtreinish): Check for httplib response from glance_http. The
        # object can't be used here because importing httplib breaks httplib2.
        # If another object from a class not imported were passed here as
        # resp this could possibly fail
        if str(type(resp)) == "<type 'instance'>":
            ctype = resp.getheader('content-type')
        else:
            try:
                ctype = resp['content-type']
            # NOTE(mtreinish): Keystone delete user responses doesn't have a
            # content-type header. (They don't have a body) So just pretend it
            # is set.
            except KeyError:
                ctype = 'application/json'

        # It is not an error response
        if resp.status < 400:
            return

        JSON_ENC = ['application/json', 'application/json; charset=utf-8']
        # NOTE(mtreinish): This is for compatibility with Glance and swift
        # APIs. These are the return content types that Glance api v1
        # (and occasionally swift) are using.
        TXT_ENC = ['text/plain', 'text/html', 'text/html; charset=utf-8',
                   'text/plain; charset=utf-8']

        if ctype.lower() in JSON_ENC:
            parse_resp = True
        elif ctype.lower() in TXT_ENC:
            parse_resp = False
        else:
            raise exceptions.UnexpectedContentType(str(resp.status),
                                                   resp=resp)

        if resp.status == 401:
            if parse_resp:
                resp_body = self._parse_resp(resp_body)
            raise exceptions.Unauthorized(resp_body, resp=resp)

        if resp.status == 403:
            if parse_resp:
                resp_body = self._parse_resp(resp_body)
            raise exceptions.Forbidden(resp_body, resp=resp)

        if resp.status == 404:
            if parse_resp:
                resp_body = self._parse_resp(resp_body)
            raise exceptions.NotFound(resp_body, resp=resp)

        if resp.status == 400:
            if parse_resp:
                resp_body = self._parse_resp(resp_body)
            raise exceptions.BadRequest(resp_body, resp=resp)

        if resp.status == 410:
            if parse_resp:
                resp_body = self._parse_resp(resp_body)
            raise exceptions.Gone(resp_body, resp=resp)

        if resp.status == 409:
            if parse_resp:
                resp_body = self._parse_resp(resp_body)
>           raise exceptions.Conflict(resp_body, resp=resp)
E           Conflict: An object with that identifier already exists

```

Tests:
* openstack_driver_mitaka_11.5.4-undercloud-vxlan.79.consoleText
  * Type: errors
  * Test: MemberSubnetTestJSON.test_member_selfips

#### Agent Version
Liberty - c311bbfb696773df0da69a28b1e938698c760fce

#### Operating System
Nightly

#### OpenStack Release
Liberty

#### Bug Severity 
Low

#### Deployment
Undercloud VXLAN

#### OpenStack Release
Liberty

**Comment by ssorenso** [comment]
Another instance:
* `openstack_driver_newton_11.6.1-undercloud-vxlan.lastSuccessfulBuild.consoleText`
  * Type: errors
  * Test: `ESDTestJSON.test_create_esd`
  * Sum: ` md5sum:ec415273d6ce981e4da82f7b745a302b`

**Comment by pjbreaux** [comment]
@ssorenso or anyone else who works on this issue, I've recreated it in the api/test_member_status.py::test_online test. The test passes, but an error results when tearing down the subnet. In this particular instance of the failure, it looks like it was the DHCP port that prevented the subnet from being deleted. This port is usually allocated when the subnet is created. It is possible that the way tempest is tearing down the subnet is not resilient to this problem. We do know that it happens in the tests here in the driver, as well as those tests we inherited from upstream in neutron-lbaas. I also observed that in other cases, subnets remained where the snat port, vip port, and DHCP port remained as well.

```
2017-10-31 19:12:45.949 1473 INFO tempest.lib.common.rest_client [req-7e9adcc3-a05f-40ba-b5bb-b9703a2112ff - - - - -] Request (MemberStatusTestJSON:tearDownClass): 409 DELETE http://172.16.1.25:9696/v2.0/subnets/99a80563-6fa7-4f56-b09d-fa6a72963cc3 0.145s
2017-10-31 19:12:45.958 1473 ERROR tempest.test [req-7e9adcc3-a05f-40ba-b5bb-b9703a2112ff - - - - -] teardown of resources failed: An object with that identifier already exists
Details: {u'message': u'Unable to complete operation on subnet 99a80563-6fa7-4f56-b09d-fa6a72963cc3: One or more ports have an IP allocation from this subnet.', u'type': u'SubnetInUse', u'detail': u''}
2017-10-31 19:12:45.958 1473 ERROR tempest.test Traceback (most recent call last):
2017-10-31 19:12:45.958 1473 ERROR tempest.test   File "/usr/local/lib/python2.7/dist-packages/tempest/test.py", line 301, in tearDownClass
2017-10-31 19:12:45.958 1473 ERROR tempest.test     teardown()
2017-10-31 19:12:45.958 1473 ERROR tempest.test   File "/home/jenkins/f5-openstack-lbaasv2-driver/f5lbaasdriver/test/tempest/tests/api/test_member_status.py", line 62, in resource_cleanup
2017-10-31 19:12:45.958 1473 ERROR tempest.test     super(MemberStatusTestJSON, cls).resource_cleanup()
2017-10-31 19:12:45.958 1473 ERROR tempest.test   File "/usr/local/lib/python2.7/dist-packages/neutron_lbaas/tests/tempest/v2/api/base.py", line 174, in resource_cleanup
2017-10-31 19:12:45.958 1473 ERROR tempest.test     super(BaseTestCase, cls).resource_cleanup()
2017-10-31 19:12:45.958 1473 ERROR tempest.test   File "/usr/local/lib/python2.7/dist-packages/tempest/api/network/base.py", line 128, in resource_cleanup
2017-10-31 19:12:45.958 1473 ERROR tempest.test     subnet['id'])
2017-10-31 19:12:45.958 1473 ERROR tempest.test   File "/usr/local/lib/python2.7/dist-packages/neutron_lbaas/tests/tempest/v2/api/base.py", line 191, in _try_delete_resource
2017-10-31 19:12:45.958 1473 ERROR tempest.test     delete_callable(*args, **kwargs)
2017-10-31 19:12:45.958 1473 ERROR tempest.test   File "/usr/local/lib/python2.7/dist-packages/tempest/lib/services/network/subnets_client.py", line 34, in delete_subnet
2017-10-31 19:12:45.958 1473 ERROR tempest.test     return self.delete_resource(uri)
2017-10-31 19:12:45.958 1473 ERROR tempest.test   File "/usr/local/lib/python2.7/dist-packages/tempest/lib/services/network/base.py", line 41, in delete_resource
2017-10-31 19:12:45.958 1473 ERROR tempest.test     resp, body = self.delete(req_uri)
2017-10-31 19:12:45.958 1473 ERROR tempest.test   File "/usr/local/lib/python2.7/dist-packages/tempest/lib/common/rest_client.py", line 290, in delete
2017-10-31 19:12:45.958 1473 ERROR tempest.test     return self.request('DELETE', url, extra_headers, headers, body)
2017-10-31 19:12:45.958 1473 ERROR tempest.test   File "/usr/local/lib/python2.7/dist-packages/tempest/lib/common/rest_client.py", line 641, in request
2017-10-31 19:12:45.958 1473 ERROR tempest.test     resp, resp_body)
2017-10-31 19:12:45.958 1473 ERROR tempest.test   File "/usr/local/lib/python2.7/dist-packages/tempest/lib/common/rest_client.py", line 709, in _error_checker
2017-10-31 19:12:45.958 1473 ERROR tempest.test     raise exceptions.Conflict(resp_body, resp=resp)
2017-10-31 19:12:45.958 1473 ERROR tempest.test Conflict: An object with that identifier already exists
2017-10-31 19:12:45.958 1473 ERROR tempest.test Details: {u'message': u'Unable to complete operation on subnet 99a80563-6fa7-4f56-b09d-fa6a72963cc3: One or more ports have an IP allocation from this subnet.', u'type': u'SubnetInUse', u'detail': u''}
2017-10-31 19:12:45.958 1473 ERROR tempest.test
```
