### ISSUE TITLE
AttributeError: 'TestL7BasicRedirectToPool' object has no attribute 'l7policy_client'

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-openstack-lbaasv2-driver#763]
* Title: AttributeError: 'TestL7BasicRedirectToPool' object has no attribute 'l7policy_client'
* Attachments:
* Details: 

##### Traceback:
```
Traceback (most recent call last):
  File "/home-local/jenkins/workspace/openstack/driver/newton/12.1.2-undercloud-vxlan/f5lbaasdriver/test/tempest/tests/scenario/test_l7policies_and_rules.py", line 165, in test_policy_redirect_pool_cookie_not_contains
    self.l7policy = self._create_l7policy(**self.redirect_pool_args)
  File "/home-local/jenkins/workspace/openstack/driver/newton/12.1.2-undercloud-vxlan/f5lbaasdriver/test/tempest/tests/scenario/f5_base.py", line 118, in _create_l7policy
    l7policy = self.l7policy_client.create_l7policy(**l7policy_kwargs)
AttributeError: 'TestL7BasicRedirectToPool' object has no attribute 'l7policy_client'
```
##### Tests:
* `openstack_driver_newton_12.1.2-undercloud-vxlan.6.consoleText`
  * Type: failures
  * Test: `TestL7BasicRedirectToPool.test_policy_redirect_pool_cookie_not_contains`

#### Agent Version
stable/newton - 2060bb6215e25a86e5dfdfebf42e1f6c5ad5d464

#### Operating System
 nightly

#### OpenStack Release
newton

#### Bug Severity 
Low

**Comment by ssorenso** [comment]
reduction sum:
55324319c0fe2e9d0d1e11966227b150

**Comment by ssorenso** [comment]
Similar signature:
```
Traceback (most recent call last):
  File "/home-local/jenkins/workspace/openstack/driver/newton/12.1.2-undercloud-vxlan/f5lbaasdriver/test/t
empest/tests/scenario/test_esd.py", line 86, in test_policy_abort_deployment
    self._create_esd('esd_demo_1')
  File "/home-local/jenkins/workspace/openstack/driver/newton/12.1.2-undercloud-vxlan/f5lbaasdriver/test/t
empest/tests/scenario/test_esd.py", line 72, in _create_esd
    self.l7policy = self._create_l7policy(**self.l7policy_args)
  File "/home-local/jenkins/workspace/openstack/driver/newton/12.1.2-undercloud-vxlan/f5lbaasdriver/test/t
empest/tests/scenario/f5_base.py", line 118, in _create_l7policy
    l7policy = self.l7policy_client.create_l7policy(**l7policy_kwargs)
AttributeError: 'TestEsdBasic' object has no attribute 'l7policy_client'
```
Tests:
* `openstack_driver_newton_11.5.4-undercloud-vxlan.72.consoleText`
  * Type: failures
  * Test: `TestL7BasicRedirectToUrl.test_policy_redirect_url_hostname_ends_with`
* `openstack_driver_newton_11.5.4-undercloud-vxlan.72.consoleText`
  * Type: failures
  * Test: `TestL7BasicRedirectToUrl.test_policy_redirect_url_file_type_not_contains`
* `openstack_driver_newton_11.5.4-undercloud-vxlan.72.consoleText`
  * Type: failures
  * Test: `TestL7BasicRedirectToUrl.test_policy_redirect_url_path_starts_with`
* Sum: 0e7b3f2234ea3d42ae32e3b2e9ed9c9f

**Comment by ssorenso** [comment]
Reduced sums:
* 102cd0bd5f9007a2e065a6b4ff3bf00c
* 610705091f880b3ee0c43e554bef06fa
* 97dcb6b0ec293c2495458b6c985c0e21
* 9e76b4cd800e57e004a5a928662897ba
* b588d751b7d3193a611d262704b1ec4a
