### ISSUE TITLE
Newton installation failing for driver/agent combo

### ISSUE THREAD

**Issue by thomsonjames** [F5Networks/f5-openstack-lbaasv2-driver#889]
* Title: Brand new Centos7 packstack AIO for newton

I've done the instructions 10 times now and every time, I do these two commands

pip install git+https://github.com/F5Networks/f5-openstack-agent@v10.1.0
pip install git+https://github.com/F5Networks/f5-openstack-lbaasv2-driver@v10.1.0

on Centos7

then I configure neutron_lbaas.conf

[service_providers]

#
# From neutron.lbaas
#

# Defines providers for advanced services using the format:
# <service_type>:<name>:<driver>[:default] (multi valued)
#service_provider =
service_provider = LOADBALANCERV2:F5Networks:neutron_lbaas.drivers.f5.driver_v2.F5LBaaSV2Driver:default

then neutron.conf

[root@newton neutron(keystone_admin)]# cat neutron.conf | grep lbaas
service_plugins=neutron_lbaas.services.loadbalancer.plugin.LoadBalancerPluginv2,router,metering

restart neutron and I get this in /var/log/neutron/server.log

2017-12-13 21:36:06.277 11965 ERROR neutron.service 
2017-12-13 21:36:06.279 11965 CRITICAL neutron [-] AttributeError: 'module' object has no attribute 'v2'
2017-12-13 21:36:06.279 11965 ERROR neutron Traceback (most recent call last):
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/bin/neutron-server", line 10, in <module>
2017-12-13 21:36:06.279 11965 ERROR neutron     sys.exit(main())
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/cmd/eventlet/server/__init__.py", line 22, in main
2017-12-13 21:36:06.279 11965 ERROR neutron     server.boot_server(_main_neutron_server)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/server/__init__.py", line 37, in boot_server
2017-12-13 21:36:06.279 11965 ERROR neutron     server_func()
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/cmd/eventlet/server/__init__.py", line 27, in _main_neutron_server
2017-12-13 21:36:06.279 11965 ERROR neutron     wsgi_eventlet.eventlet_wsgi_server()
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/server/wsgi_eventlet.py", line 24, in eventlet_wsgi_server
2017-12-13 21:36:06.279 11965 ERROR neutron     neutron_api = service.serve_wsgi(service.NeutronApiService)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/service.py", line 90, in serve_wsgi
2017-12-13 21:36:06.279 11965 ERROR neutron     LOG.exception(_LE('Unrecoverable error: please check log '
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2017-12-13 21:36:06.279 11965 ERROR neutron     self.force_reraise()
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2017-12-13 21:36:06.279 11965 ERROR neutron     six.reraise(self.type_, self.value, self.tb)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/service.py", line 87, in serve_wsgi
2017-12-13 21:36:06.279 11965 ERROR neutron     service.start()
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/service.py", line 63, in start
2017-12-13 21:36:06.279 11965 ERROR neutron     self.wsgi_app = _run_wsgi(self.app_name)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/service.py", line 289, in _run_wsgi
2017-12-13 21:36:06.279 11965 ERROR neutron     app = config.load_paste_app(app_name)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/common/config.py", line 125, in load_paste_app
2017-12-13 21:36:06.279 11965 ERROR neutron     app = loader.load_app(app_name)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/oslo_service/wsgi.py", line 353, in load_app
2017-12-13 21:36:06.279 11965 ERROR neutron     return deploy.loadapp("config:%s" % self.config_path, name=name)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
2017-12-13 21:36:06.279 11965 ERROR neutron     return loadobj(APP, uri, name=name, **kw)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
2017-12-13 21:36:06.279 11965 ERROR neutron     return context.create()
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
2017-12-13 21:36:06.279 11965 ERROR neutron     return self.object_type.invoke(self)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 144, in invoke
2017-12-13 21:36:06.279 11965 ERROR neutron     **context.local_conf)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
2017-12-13 21:36:06.279 11965 ERROR neutron     val = callable(*args, **kw)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/paste/urlmap.py", line 25, in urlmap_factory
2017-12-13 21:36:06.279 11965 ERROR neutron     app = loader.get_app(app_name, global_conf=global_conf)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 350, in get_app
2017-12-13 21:36:06.279 11965 ERROR neutron     name=name, global_conf=global_conf).create()
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
2017-12-13 21:36:06.279 11965 ERROR neutron     return self.object_type.invoke(self)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 144, in invoke
2017-12-13 21:36:06.279 11965 ERROR neutron     **context.local_conf)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
2017-12-13 21:36:06.279 11965 ERROR neutron     val = callable(*args, **kw)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/auth.py", line 71, in pipeline_factory
2017-12-13 21:36:06.279 11965 ERROR neutron     app = loader.get_app(pipeline[-1])
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 350, in get_app
2017-12-13 21:36:06.279 11965 ERROR neutron     name=name, global_conf=global_conf).create()
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
2017-12-13 21:36:06.279 11965 ERROR neutron     return self.object_type.invoke(self)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
2017-12-13 21:36:06.279 11965 ERROR neutron     return fix_call(context.object, context.global_conf, **context.local_conf)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
2017-12-13 21:36:06.279 11965 ERROR neutron     val = callable(*args, **kw)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/api/v2/router.py", line 72, in factory
2017-12-13 21:36:06.279 11965 ERROR neutron     return cls(**local_config)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/api/v2/router.py", line 76, in __init__
2017-12-13 21:36:06.279 11965 ERROR neutron     plugin = manager.NeutronManager.get_plugin()
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/manager.py", line 244, in get_plugin
2017-12-13 21:36:06.279 11965 ERROR neutron     return weakref.proxy(cls.get_instance().plugin)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/manager.py", line 238, in get_instance
2017-12-13 21:36:06.279 11965 ERROR neutron     cls._create_instance()
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py", line 271, in inner
2017-12-13 21:36:06.279 11965 ERROR neutron     return f(*args, **kwargs)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/manager.py", line 224, in _create_instance
2017-12-13 21:36:06.279 11965 ERROR neutron     cls._instance = cls()
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/manager.py", line 137, in __init__
2017-12-13 21:36:06.279 11965 ERROR neutron     self._load_service_plugins()
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/manager.py", line 197, in _load_service_plugins
2017-12-13 21:36:06.279 11965 ERROR neutron     provider)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/manager.py", line 160, in _get_plugin_instance
2017-12-13 21:36:06.279 11965 ERROR neutron     return plugin_class()
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron_lbaas/services/loadbalancer/plugin.py", line 83, in __init__
2017-12-13 21:36:06.279 11965 ERROR neutron     self._load_drivers()
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron_lbaas/services/loadbalancer/plugin.py", line 98, in _load_drivers
2017-12-13 21:36:06.279 11965 ERROR neutron     constants.LOADBALANCERV2, self)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/services/service_base.py", line 73, in load_drivers
2017-12-13 21:36:06.279 11965 ERROR neutron     provider['driver'], plugin
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/oslo_utils/importutils.py", line 44, in import_object
2017-12-13 21:36:06.279 11965 ERROR neutron     return import_class(import_str)(*args, **kwargs)
2017-12-13 21:36:06.279 11965 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron_lbaas/drivers/f5/driver_v2.py", line 43, in __init__
2017-12-13 21:36:06.279 11965 ERROR neutron     self.f5 = f5lbaasdriver.v2.bigip.driver_v2.F5DriverV2(plugin, env)
2017-12-13 21:36:06.279 11965 ERROR neutron AttributeError: 'module' object has no attribute 'v2'
2017-12-13 21:36:06.279 11965 ERROR neutron

**Comment by amudukutore** [comment]
@thomsonjames - are you following all the instructions in the documentation as listed here: http://clouddocs.f5.com/products/openstack/lbaasv2-driver/master/#installation

**Comment by amudukutore** [comment]
@thomsonjames - please let us know if this is still an issue after following docs. We can revise docs based on that. If this is no longer an issue, I will close this out in a week,.

**Comment by adeel2020** [comment]
I have similar issue with neutron constant



Traceback (most recent call last):
  File "/usr/local/bin/oslo-config-generator", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/oslo_config/generator.py", line 782, in main
    generate(conf)
  File "/usr/local/lib/python3.8/dist-packages/oslo_config/generator.py", line 743, in generate
    groups = _get_groups(_list_opts(conf.namespace))
  File "/usr/local/lib/python3.8/dist-packages/oslo_config/generator.py", line 483, in _list_opts
    loaders = _get_raw_opts_loaders(namespaces)
  File "/usr/local/lib/python3.8/dist-packages/oslo_config/generator.py", line 423, in _get_raw_opts_loaders
    mgr = stevedore.named.NamedExtensionManager(
  File "/usr/local/lib/python3.8/dist-packages/stevedore/named.py", line 78, in __init__
    extensions = self._load_plugins(invoke_on_load,
  File "/usr/local/lib/python3.8/dist-packages/stevedore/extension.py", line 203, in _load_plugins
    self._on_load_failure_callback(self, ep, err)
  File "/usr/local/lib/python3.8/dist-packages/stevedore/extension.py", line 191, in _load_plugins
    ext = self._load_one_plugin(ep,
  File "/usr/local/lib/python3.8/dist-packages/stevedore/named.py", line 156, in _load_one_plugin
    return super(NamedExtensionManager, self)._load_one_plugin(
  File "/usr/local/lib/python3.8/dist-packages/stevedore/extension.py", line 223, in _load_one_plugin
    plugin = ep.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/stack/neutron/neutron/opts.py", line 21, in <module>
    import neutron.agent.securitygroups_rpc
  File "/opt/stack/neutron/neutron/agent/securitygroups_rpc.py", line 26, in <module>
    from neutron.common import _constants as common_constants
  File "/opt/stack/neutron/neutron/common/_constants.py", line 79, in <module>
    constants.DEVICE_OWNER_DISTRIBUTED]
AttributeError: module 'neutron_lib.constants' has no attribute 'DEVICE_OWNER_DISTRIBUTED'
+lib/neutron-legacy:_configure_neutron_common:1  exit_trap
+./stack.sh:exit_trap:489                  local r=1
++./stack.sh:exit_trap:490                  jobs -p
+./stack.sh:exit_trap:490                  jobs=
+./stack.sh:exit_trap:493                  [[ -n '' ]]
+./stack.sh:exit_trap:499                  '[' -f /tmp/tmp.APJLOJV47M ']'
+./stack.sh:exit_trap:500                  rm /tmp/tmp.APJLOJV47M
+./stack.sh:exit_trap:504                  kill_spinner
+./stack.sh:kill_spinner:399               '[' '!' -z '' ']'
+./stack.sh:exit_trap:506                  [[ 1 -ne 0 ]]
+./stack.sh:exit_trap:507                  echo 'Error on exit'
Error on exit
+./stack.sh:exit_trap:509                  type -p generate-subunit
+./stack.sh:exit_trap:510                  generate-subunit 1598784338 256 fail
+./stack.sh:exit_trap:512                  [[ -z /opt/stack/logs ]]
+./stack.sh:exit_trap:515                  /usr/bin/python3.8 /home/stack/devstack/tools/worlddump.py -d /opt/stack/logs
