### ISSUE TITLE
Running the Overcloud tests errors out

### ISSUE THREAD

**Issue by szakeri** [F5Networks/f5-openstack-lbaasv2-driver#893]
* Details: 
Running the tempest tests errors out with a Server fault

#### Agent Version
Newton

#### Operating System
<Fill in the host OS of the machine running the agent, such as CentOS 7>

#### OpenStack Release
Newton

#### Bug Severity 
For bugs enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

#### Deployment
I ran neutron-lbaas tempest api tests against an overcloud-12.1.2-newton stack and got errors for all the tests.
The test error is:
```
            if resp.status == 501:
                raise exceptions.NotImplemented(resp_body, resp=resp,
                                                message=message)
            else:
                raise exceptions.ServerFault(resp_body, resp=resp,
>                                            message=message)
E               ServerFault: Got server fault
E               Details: An error happened in the driver

JSON_ENC   = ['application/json', 'application/json; charset=utf-8']
TXT_ENC    = ['text/plain', 'text/html', 'text/html; charset=utf-8', 'text/plain; charset=utf-8']
body       = '{"loadbalancer": {"vip_subnet_id": "a3e850d4-93e9-4b6f-b961-44583f89d69b", "tenant_id": "7fae639d2f464d34aaff2a819bf766c4"}}'
ctype      = 'application/json; charset=UTF-8'
headers    = {'Accept': 'application/json', 'Content-Type': 'application/json'}
message    = 'An error happened in the driver'
method     = 'POST'
parse_resp = True
resp       = {'status': '500', 'content-length': '101', 'content-location': 'http://10.190....t=UTF-8', 'x-openstack-request-id': 'req-684fc079-9301-4c3b-8778-fb89aed6a242'}
resp_body  = {'detail': '', 'message': 'An error happened in the driver', 'type': 'DriverError'}
self       = <neutron_lbaas.tests.tempest.v2.clients.load_balancers_client.LoadBalancersClientJSON object at 0x107b040d0>
url        = 'v2.0/lbaas/loadbalancers'

```
And the neutron server log file output is:
```

2018-01-17 17:14:46.715 25350 DEBUG f5lbaasdriver.v2.bigip.service_builder [req-863e0b7f-6e61-4411-b754-1ad9cfa11c99 977a545df100468b8f8535f13f4d8021 19e43b45de594327b91b1be3ed943828 - - -] f5lbaasdriver.v2.bigip.service_builder.LBaaSv2ServiceBuilder method _get_extended_loadbalancer called with arguments (<neutron.context.Context object at 0x7ef7ed0>, <neutron_lbaas.services.loadbalancer.data_models.LoadBalancer object at 0x7ef99d0>) {} wrapper /usr/lib/python2.7/site-packages/oslo_log/helpers.py:45
2018-01-17 17:14:46.733 25350 DEBUG f5lbaasdriver.v2.bigip.service_builder [req-863e0b7f-6e61-4411-b754-1ad9cfa11c99 977a545df100468b8f8535f13f4d8021 19e43b45de594327b91b1be3ed943828 - - -] f5lbaasdriver.v2.bigip.service_builder.LBaaSv2ServiceBuilder method _get_subnet_cached called with arguments (<neutron.context.Context object at 0x7ef7ed0>, u'dd851ef6-c42e-4ca7-9738-2b1a902e2258') {} wrapper /usr/lib/python2.7/site-packages/oslo_log/helpers.py:45
2018-01-17 17:14:46.766 25350 DEBUG f5lbaasdriver.v2.bigip.service_builder [req-863e0b7f-6e61-4411-b754-1ad9cfa11c99 977a545df100468b8f8535f13f4d8021 19e43b45de594327b91b1be3ed943828 - - -] f5lbaasdriver.v2.bigip.service_builder.LBaaSv2ServiceBuilder method _get_network_cached called with arguments (<neutron.context.Context object at 0x7ef7ed0>, u'f2349248-5f3f-4783-83c2-461666d8b50f') {} wrapper /usr/lib/python2.7/site-packages/oslo_log/helpers.py:45
2018-01-17 17:14:46.799 25350 ERROR f5lbaasdriver.v2.bigip.driver_v2 [req-863e0b7f-6e61-4411-b754-1ad9cfa11c99 977a545df100468b8f8535f13f4d8021 19e43b45de594327b91b1be3ed943828 - - -] Exception: loadbalancer create: can only concatenate list (not "unicode") to list
2018-01-17 17:14:46.800 25350 ERROR neutron_lbaas.services.loadbalancer.plugin [req-863e0b7f-6e61-4411-b754-1ad9cfa11c99 977a545df100468b8f8535f13f4d8021 19e43b45de594327b91b1be3ed943828 - - -] There was an error in the driver
2018-01-17 17:14:46.800 25350 ERROR neutron_lbaas.services.loadbalancer.plugin Traceback (most recent call last):
2018-01-17 17:14:46.800 25350 ERROR neutron_lbaas.services.loadbalancer.plugin   File "/usr/lib/python2.7/site-packages/neutron_lbaas/services/loadbalancer/plugin.py", line 486, in _call_driver_operation
2018-01-17 17:14:46.800 25350 ERROR neutron_lbaas.services.loadbalancer.plugin     driver_method(context, db_entity)
2018-01-17 17:14:46.800 25350 ERROR neutron_lbaas.services.loadbalancer.plugin   File "/usr/lib/python2.7/site-packages/neutron_lbaas/drivers/f5/driver_v2.py", line 81, in create
2018-01-17 17:14:46.800 25350 ERROR neutron_lbaas.services.loadbalancer.plugin     self.driver.f5.loadbalancer.create(context, lb)
2018-01-17 17:14:46.800 25350 ERROR neutron_lbaas.services.loadbalancer.plugin   File "/usr/lib/python2.7/site-packages/oslo_log/helpers.py", line 46, in wrapper
2018-01-17 17:14:46.800 25350 ERROR neutron_lbaas.services.loadbalancer.plugin     return method(*args, **kwargs)
2018-01-17 17:14:46.800 25350 ERROR neutron_lbaas.services.loadbalancer.plugin   File "/usr/lib/python2.7/site-packages/f5lbaasdriver/v2/bigip/driver_v2.py", line 236, in create
2018-01-17 17:14:46.800 25350 ERROR neutron_lbaas.services.loadbalancer.plugin     raise e
2018-01-17 17:14:46.800 25350 ERROR neutron_lbaas.services.loadbalancer.plugin TypeError: can only concatenate list (not "unicode") to list
2018-01-17 17:14:46.800 25350 ERROR neutron_lbaas.services.loadbalancer.plugin
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource [req-863e0b7f-6e61-4411-b754-1ad9cfa11c99 977a545df100468b8f8535f13f4d8021 19e43b45de594327b91b1be3ed943828 - - -] create failed
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource Traceback (most recent call last):
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 84, in resource
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource     result = method(request=request, **args)
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 410, in create
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource     return self._create(request, body, **kwargs)
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 148, in wrapper
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource     ectxt.value = e.inner_exc
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource     self.force_reraise()
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource     six.reraise(self.type_, self.value, self.tb)
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 138, in wrapper
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource     return f(*args, **kwargs)
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 521, in _create
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource     obj = do_create(body)
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 503, in do_create
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource     request.context, reservation.reservation_id)
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource     self.force_reraise()
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource     six.reraise(self.type_, self.value, self.tb)
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 496, in do_create
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource     return obj_creator(request.context, **kwargs)
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron_lbaas/services/loadbalancer/plugin.py", line 583, in create_loadbalancer
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource     self._call_driver_operation(context, create_method, lb_db)
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron_lbaas/services/loadbalancer/plugin.py", line 494, in _call_driver_operation
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource     raise loadbalancerv2.DriverError()
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource DriverError: An error happened in the driver
2018-01-17 17:14:46.814 25350 ERROR neutron.api.v2.resource
```

**Comment by amudukutore** [comment]
The fix for https://github.com/F5Networks/f5-openstack-agent/issues/1215 addresses this issue.
